// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjogdsojplphvoesnzwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqb2dkc29qcGxwaHZvZXNuendkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNjQ1NDMsImV4cCI6MjA2Njg0MDU0M30.vq0k24NnWe03vWwHGAu1c51F8AhwodRNTOr7jqpMI1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});